# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            sysdump.de
tagline:          ..da hilft auch kein debugging mehr!
url:              http://sysdump.de
paginate:         8
baseurl:          /
author:
  name:           derMerl
  url:            https://twitter.com/dermerl
  email:          merl@sysdump.de

