# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sysdump.de
tagline:          '..da hilft auch kein debugging mehr!'
url:              http://sysdump.de
baseurl:          /

author:
  name:           derMerl
  url:            https://twitter.com/dermerl
  email:          merl@sysdump.de

paginate:         8